### ISSUE TITLE
minor typo in title

### ISSUE THREAD

**Issue by ianrobertdouglas** [settermjd/vim-for-technical-writers#3]
vim-for-technial-writers

Should be:

vim-for-technical-writers

**Comment by settermjd** [comment]
Thanks for spotting it. I'll fix it soonish.
Ian Douglas notifications@github.com schrieb am Fr., 8. Mai 2015 um 18:07:

**Comment by settermjd** [comment]
Ok, soonish sure wasn't soonish.

**Comment by settermjd** [comment]
Kinda embarrassing that one. But, done.
